name: github-actions-2
on: push
jobs:
  lint:
    runs-on: my-runner
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: ci
        run: npm ci
  test:
    needs: lint 
    runs-on: my-runner
    steps:   
      - name: checkout the code
        uses: actions/checkout@v3
      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: npm ci
        run: npm ci    
  build: 
    needs: test
    runs-on: my-runner 
    steps: 
    - name: checkout the code
      uses: actions/checkout@v3
    - name: node setup
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: npm ci
      run: npm ci
  docker-build-push:
    needs: build
    runs-on: my-runner
    steps:
    - name: checkout
      uses: actions/checkout@v3 
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: devendranathashok/my-microservice
       #tags: ${{ steps.meta.outputs.tags }}
        tags: ${{ env.hash }}
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKERUSER }}
        password: ${{ secrets.DOCKERPASSWORD }}            
