name: github-actions-2
on: push
jobs:
  lint:
    runs-on: my-runner
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: ci
        run: npm ci    
      - name: lint
        run: npm run lint
  test:
    needs: lint 
    runs-on: my-runner
    steps:   
      - name: checkout the code
        uses: actions/checkout@v3
      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: npm ci
        run: npm ci    
      - name: test
        run: npm run test
  build: 
    needs: test
    runs-on: my-runner 
    steps: 
    - name: checkout the code
      uses: actions/checkout@v3
    - name: node setup
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: npm ci
      run: npm ci    
    - name: build
      run: npm run build       
